### ISSUE TITLE
Should we add the last week's slide to README.md as a reference?

### ISSUE THREAD

**Issue by imambungo** [airlab-unsri/basic-python-course#2]
https://docs.google.com/presentation/d/1xWg1Zu-K8P5FYw8J0_6Z3oS98hGoksHINjuH7XG-ydE/edit#slide=id.gc6fa3c898_0_22

**Comment by faisalmorensya** [comment]
i think it is necessary, good point

**Comment by ariefrahmansyah** [comment]
I prefer to update our README.md to only include the descriptions, subjects, and slides for all of our sessions? So there will be no code example there because everyone should have it on their folder.
What do you guys think?

**Comment by imambungo** [comment]
@ariefrahmansyah I agree :+1:

**Comment by faisalmorensya** [comment]
I will close this issue

**Comment by ariefrahmansyah** [comment]
Why do you want to close this issue? @lloistborn
